language: python
sudo: required
services:
  - postgresql
  - redis-server
python:
  - "2.7"
env:
  - CKAN_VERSION=2.8.2 JSONPATCH_VERSION=0.5-beta

install: bash bin/travis-build.bash
script: bash bin/travis-run.bash
after_success: coveralls
