language: python
sudo: required
services: postgresql

python:
  - "2.7"
env:
  - CKAN_VERSION=2.8.2 JSONPATCH_VERSION=0.4-alpha

install: bash bin/travis-build.bash
script: bash bin/travis-run.bash
after_success: coveralls
